### ISSUE TITLE
Failed at the db-nuodb@2.0.2 install script 'make build && make install'

### ISSUE THREAD

**Issue by XiayidanAlimu** [nuodb/node-db-nuodb#28]
I have installed the lasted version of NuoDB and Node.js and configured the environment variables, ans I run the command `npm install db-nuodb` I get the error like the following:
 
![error nuodb npm node js install](https://cloud.githubusercontent.com/assets/22473904/25003906/ea9e6070-2051-11e7-954c-471ca3b4d109.PNG)
Is there anyone who can tell me how to resolve this problem, i have been blocked by this for two days and I almost most my confidence on it :(
Thank you for your response

**Comment by treilly-nuodb** [comment]
The driver has only been tested on systems with GNU tools (OSX/Linux).    It could be made to work on Win32 but it will require some serious Win32 release engineering chops.   Do you have access to a Linux or OSX system?

**Comment by XiayidanAlimu** [comment]
**Thank your for your response. Yes, I have tried the alternative approach that you proposed. I used a machine Linux instead of Windows, and redo all the pre-requirements (have the latest version of node.js, npm, and nuodb installed and also have environment variables set correctly), and when I type in the command `npm install db-nuodb`, I still got some errors, I searched but I still had no idea where were those problems coming from...** 
$ node -v
v6.10.2
$ npm -v
3.10.10
$ nuodb --version
NuoDB Server build 2.6.1-5-7c128c01f3
$ npm install db-nuodb

> db-nuodb@2.0.2 install /home/users/svc_xadvisor/node_modules/db-nuodb
> make build && make install

# configure and build npm module
node-gyp configure
node-gyp build
make[1]: Entering directory `/home/users/svc_xadvisor/node_modules/db-nuodb/build'
  CXX(target) Release/obj.target/nuodb_bindings/lib/node-db/binding.o
In file included from ../lib/node-db/./binding.h:5,
                 from ../lib/node-db/binding.cc:2:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:345: error: expected unqualified-id before ‘using’
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:362: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:369: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:373: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: At global scope:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:481: error: expected unqualified-id before ‘using’
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:820: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:845: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:857: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: At global scope:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:882: error: expected unqualified-id before ‘using’
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:1119: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:1125: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:3278: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: At global scope:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:4498: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:4514: error: ‘nullptr’ was not declared in this scope
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h: In member function ‘v8::Local<T> v8::MaybeLocal<T>::ToLocalChecked()’:
/u/users/svc_xadvisor/.node-gyp/6.10.2/include/node/v8.h:7538: error: ‘nullptr’ was not declared in this scope
In file included from ../lib/node-db/./binding.h:12,
                 from ../lib/node-db/binding.cc:2:
../lib/node-db/././events.h: At global scope:
../lib/node-db/././events.h:21: error: ‘v8::Handle’ has not been declared
../lib/node-db/././events.h:21: error: expected ‘,’ or ‘...’ before ‘<’ token
In file included from ../lib/node-db/./binding.h:14,
                 from ../lib/node-db/binding.cc:2:
../lib/node-db/././query.h:25: error: ‘v8::Handle’ has not been declared
../lib/node-db/././query.h:25: error: expected ‘,’ or ‘...’ before ‘<’ token
../lib/node-db/././query.h:27: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:27: error: invalid use of ‘::’
../lib/node-db/././query.h:27: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:55: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:55: error: invalid use of ‘::’
../lib/node-db/././query.h:55: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:56: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:56: error: invalid use of ‘::’
../lib/node-db/././query.h:56: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:57: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:57: error: invalid use of ‘::’
../lib/node-db/././query.h:57: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:58: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:58: error: invalid use of ‘::’
../lib/node-db/././query.h:58: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:59: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:59: error: invalid use of ‘::’
../lib/node-db/././query.h:59: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:60: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:60: error: invalid use of ‘::’
../lib/node-db/././query.h:60: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:61: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:61: error: invalid use of ‘::’
../lib/node-db/././query.h:61: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:62: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:62: error: invalid use of ‘::’
../lib/node-db/././query.h:62: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:63: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:63: error: invalid use of ‘::’
../lib/node-db/././query.h:63: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:64: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:64: error: invalid use of ‘::’
../lib/node-db/././query.h:64: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:65: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:65: error: invalid use of ‘::’
../lib/node-db/././query.h:65: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:66: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:66: error: invalid use of ‘::’
../lib/node-db/././query.h:66: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:67: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:67: error: invalid use of ‘::’
../lib/node-db/././query.h:67: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:68: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:68: error: invalid use of ‘::’
../lib/node-db/././query.h:68: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:69: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:69: error: invalid use of ‘::’
../lib/node-db/././query.h:69: error: expected ‘;’ before ‘<’ token
../lib/node-db/././query.h:70: error: ‘uv_async_t’ does not name a type
../lib/node-db/././query.h:71: error: ‘uv_work_t’ has not been declared
../lib/node-db/././query.h:72: error: ‘uv_work_t’ has not been declared
../lib/node-db/././query.h:77: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/././query.h:77: error: invalid use of ‘::’
../lib/node-db/././query.h:77: error: expected ‘;’ before ‘<’ token
In file included from ../lib/node-db/binding.cc:2:
../lib/node-db/./binding.h:31: error: ‘v8::Handle’ has not been declared
../lib/node-db/./binding.h:31: error: expected ‘,’ or ‘...’ before ‘<’ token
../lib/node-db/./binding.h:32: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/./binding.h:32: error: invalid use of ‘::’
../lib/node-db/./binding.h:32: error: expected ‘;’ before ‘<’ token
../lib/node-db/./binding.h:33: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/./binding.h:33: error: invalid use of ‘::’
../lib/node-db/./binding.h:33: error: expected ‘;’ before ‘<’ token
../lib/node-db/./binding.h:34: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/./binding.h:34: error: invalid use of ‘::’
../lib/node-db/./binding.h:34: error: expected ‘;’ before ‘<’ token
../lib/node-db/./binding.h:35: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/./binding.h:35: error: invalid use of ‘::’
../lib/node-db/./binding.h:35: error: expected ‘;’ before ‘<’ token
../lib/node-db/./binding.h:36: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/./binding.h:36: error: invalid use of ‘::’
../lib/node-db/./binding.h:36: error: expected ‘;’ before ‘<’ token
../lib/node-db/./binding.h:37: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/./binding.h:37: error: invalid use of ‘::’
../lib/node-db/./binding.h:37: error: expected ‘;’ before ‘<’ token
../lib/node-db/./binding.h:38: error: ‘uv_async_t’ does not name a type
../lib/node-db/./binding.h:39: error: ‘uv_work_t’ has not been declared
../lib/node-db/./binding.h:40: error: ‘uv_work_t’ has not been declared
../lib/node-db/./binding.h:43: error: ISO C++ forbids declaration of ‘Handle’ with no type
../lib/node-db/./binding.h:43: error: invalid use of ‘::’
../lib/node-db/./binding.h:43: error: expected ‘;’ before ‘<’ token
../lib/node-db/binding.cc: In destructor ‘virtual node_db::Binding::~Binding()’:
../lib/node-db/binding.cc:9: error: ‘cb_destroy’ is not a member of ‘node’
../lib/node-db/binding.cc: At global scope:
../lib/node-db/binding.cc:13: error: ‘uv_async_t’ does not name a type
../lib/node-db/binding.cc:15: error: variable or field ‘Init’ declared void
../lib/node-db/binding.cc:15: error: ‘Handle’ is not a member of ‘v8’
../lib/node-db/binding.cc:15: error: expected primary-expression before ‘>’ token
../lib/node-db/binding.cc:15: error: ‘target’ was not declared in this scope
../lib/node-db/binding.cc:15: error: expected primary-expression before ‘constructorTemplate’
make[1]: *** [Release/obj.target/nuodb_bindings/lib/node-db/binding.o] Error 1
make[1]: Leaving directory `/home/users/svc_xadvisor/node_modules/db-nuodb/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/users/svc_xadvisor/install_dir/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "/home/users/svc_xadvisor/install_dir/nodejs/bin/node" "/home/users/svc_xadvisor/install_dir/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/users/svc_xadvisor/node_modules/db-nuodb
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
make: *** [build] Error 1
npm ERR! Linux 2.6.32-431.el6.x86_64
npm ERR! argv "/home/users/svc_xadvisor/install_dir/nodejs/bin/node" "/home/users/svc_xadvisor/install_dir/nodejs/bin/npm" "install" "db-nuodb"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! db-nuodb@2.0.2 install: `make build && make install`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the db-nuodb@2.0.2 install script 'make build && make install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the db-nuodb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build && make install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs db-nuodb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls db-nuodb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/users/svc_xadvisor/npm-debug.log
**Do you have any idea about it ? or is there some evident errors are showed in my case ...
Thank you for your response :)**

**Comment by KelviNosse** [comment]
It seems it requires only Node.js version <= 0.10.X
I suggest to use nvm.

**Comment by XiayidanAlimu** [comment]
hi, thank you for your response, i want to make sure if you suggest me to use node.js version <=0.10.x in windows ?

**Comment by KelviNosse** [comment]
Yes, if you already have installed some other version of node.js greater than 0.10.x, you can use
nvm (node version manager) for windows, to switch from one version to another.
You can find more here: https://github.com/coreybutler/nvm-windows
Good luck!

**Comment by XiayidanAlimu** [comment]
Thank you, I tried, but it doesn't work out. 
`C:\Users\xau1>npm install db-nuodb
npm WARN package.json xau1@2.0.3 No README data
npm WARN package.json bcrypt-pbkdf@1.0.1 No repository field.
npm WARN package.json punycode@1.4.1 punycode is also the name of a node core module.

> db-nuodb@2.0.2 install C:\Users\xau1\node_modules\db-nuodb
> make build && make install

# configure and build npm module
node-gyp configure

C:\Users\xau1\node_modules\db-nuodb>node "C:\Users\xau1\AppData\Roaming\nvm\v0.10.32\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure
gyp ERR! configure error
gyp ERR! stack Error: spawn ENOENT
gyp ERR! stack     at errnoException (child_process.js:1001:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:792:34)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Users\\xau1\\AppData\\Roaming\\nvm\\v0.10.32\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd C:\Users\xau1\node_modules\db-nuodb
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
make: *** [build] Error 1

npm ERR! db-nuodb@2.0.2 install: `make build && make install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the db-nuodb@2.0.2 install script.
npm ERR! This is most likely a problem with the db-nuodb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make build && make install
npm ERR! You can get their info via:
npm ERR!     npm owner ls db-nuodb
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Users\\xau1\\AppData\\Roaming\\nvm\\v0.10.32\\\\node.exe" "C:\\Users\\xau1\\AppData\\Roaming\\nvm\\v0.10.32\\node_modules\\npm\\bin\\npm-cli.js" "install" "db-nuodb"
npm ERR! cwd C:\Users\xau1
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE

> db-nuodb@2.0.2 uninstall C:\Users\xau1\node_modules\db-nuodb
> make clean

# remove module dependencies
node-gyp clean
`
you have succed at installing db-nuodb in your machine windows ?
